apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2 # 指定 3 个副本
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # 使用 LoadBalancer 类型以从外部访问

  # 如果你在 eks 里面使用 loadbalancer , 然后会生成一个elb ,直接公网可以访问，这就是eks 的强大之处